services:
  - type: web
    name: virat-kohli
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: onboarding@resend.dev
      - key: RESEND_TO_EMAIL
        value: harshadsawarkar05@gmail.com
